name: Deploy DEV

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.DEV_SSH_PRIVATE_KEY_B64 }}" | base64 --decode > ~/.ssh/github_actions_dev
          chmod 600 ~/.ssh/github_actions_dev

          ssh-keyscan -H ${{ secrets.DEV_FRONTEND_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          ssh-keygen -lf ~/.ssh/github_actions_dev

      - name: Test SSH
        run: |
          ssh \
            -i ~/.ssh/github_actions_dev \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_FRONTEND_HOST }} \
            "echo 'SSH Connection Successful'"

      - name: Deploy Frontend
        run: |
          ssh \
            -i ~/.ssh/github_actions_dev \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_FRONTEND_HOST }} << 'EOF'

          set -e

          cd /home/rohit/simple-bank-dev

          git fetch origin
          git checkout dev
          git reset --hard origin/dev

          cd frontend

          docker compose down || true
          docker compose up -d --build

          EOF

      - name: Deploy Backend
        run: |
          ssh \
            -i ~/.ssh/github_actions_dev \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            -J ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_FRONTEND_HOST }} \
            ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_BACKEND_HOST }} << 'EOF'

          set -e

          cd /home/rohit/simple-bank-dev

          git fetch origin
          git checkout dev
          git reset --hard origin/dev

          cd backend

          docker compose down || true
          docker compose up -d --build

          EOF

      - name: Health Check
        run: |
          curl -f https://dev.simplebankgcp.biharibabu.info
